// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7baed208-cd1b-4900-a2d0-aa3eb4005372",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8HlEk7DFL",
    "aws_user_pools_web_client_id": "ptbf4ghj0snl68kq1ec23e1r7",
    "aws_user_files_s3_bucket": "sleephackerbucket",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_mobile_analytics_app_id": "7cfb2ce4a1634ccfa91850a8c6b461b7",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "sleephackerhostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://sleephackerhostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
